services:
  - type: web
<<<<<<< HEAD
    name: my-django-app
    env: python
    pythonVersion: 3.12.2
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn customer360.wsgi:application"
=======
    name: mon-projet-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn customer360.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.2"
>>>>>>> 41ed61e067f579cb891e14aaed63a9555d6a6d35
