services:
  - type: web
    name: my-django-app  # Ou "mon-projet-django", choisis un seul nom
    env: python
    pythonVersion: 3.12.2
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn customer360.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.2"
