services:
  - type: web
    name: mon-projet-django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn customer360.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.2"
