services:
  - type: web
    name: customer360
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn customer360.wsgi:application"
